import Head from 'next/head'
import Categories from '../components/Categories'
import FindYourConformHome from '../components/FindYourConformHome'
import HeroSection from '../components/HeroSection'
import Line from '../components/Line'
import Products from '../components/Products'
import Properties from '../components/Properties'
import TopBar from '../components/TopBar'



export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      {/* Topbar */}
      <TopBar />
      <Line />

      {/* hero section */}
      <HeroSection />
      {/* Categories */}
      <Categories />
      <Line />
      {/* Properties */}
      <Properties />
      {/* products */}
      <Products />
      {/* findyourconformhome */}
      <FindYourConformHome/>
    </>
  )
}
