import Head from 'next/head'
import Categories from '../components/Categories'
import Collection from '../components/Collection'
import DailyEssentials from '../components/DailyEssentials'
import FeaturedCatogories from '../components/FeaturedCatogories'
import FindYourConformHome from '../components/FindYourConformHome'
// import Footer from '../components/Footer'
// import FooterInfo from '../components/FooterInfo'
import HeroSection from '../components/HeroSection'
import HolidayDestination from '../components/HolidayDestination'
import LatestBlogs from '../components/LatestBlogs'
import Line from '../components/Line'
import Newsletter from '../components/Newsletter'
import Products from '../components/Products'
import Properties from '../components/Properties'
import TopBar from '../components/TopBar'
// import RelatedSearch from '../components/RelatedSearch'
// import TopBar from '../components/TopBar'



export default function Home() {


  return (
    <>
      <Head>
        <title>DealSala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <div className='overflow-hidden'>
        {/* Topbar */}
        <TopBar />
        <Line />

        {/* hero section */}
        <HeroSection />
        {/* Categories */}
        <Categories />
        <Line />
        {/* Properties */}
        <Properties />
        {/* products */}
        <Products />
        {/* findyourconformhome */}
        <FindYourConformHome />
        {/* daily essentials */}
        <DailyEssentials />
        {/* collection */}
        <Collection />  
        {/* FeaturedCatogories */}
        <FeaturedCatogories />
        {/* holidayDestination */}
        <HolidayDestination />
        {/* Latest Blogs */}
        <LatestBlogs />
        {/* related search */}
        {/* <RelatedSearch /> */}
        {/* newsletter */}
        {/* <Newsletter /> */}
        {/* footerinfo */}
        {/* <FooterInfo /> */}
        {/* Footer */}
        {/* <Footer /> */}
      </div>
    </>
  )
}
